# Site settings
title: Where No Dev Has Gone Before...
email: timcandid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software developer with 10 years of experince in large-scale enterprise applications development and technical
  management; Sun Certified Java Developer, Scrum Alliance Certified Scrum Master, Python enthusiast and Scala novice.
  Here you'll find my personal experience on various development technologies and approaches I want to share with you.
  You know, sharing is good.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://candidtim.github.io" # the base hostname & protocol for your site
twitter_username: candidtim
github_username:  candidtim

# Build settings
markdown: kramdown
