# Site settings
title: Tim's Journal
description: > # this means to ignore newlines until "baseurl:"
  I work in software development industry for almost 20 years now and have
  experience in various B2B domains ranging from enterprise integration
  software to FinTech and PropTech, in both large multinational and start-up
  environments. In this irregularly updated blog I keep notes of some of my
  findings, when I think they might be useful for someone else.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://candidtim.github.io" # the base hostname & protocol for your site
github_username:  candidtim

# Build settings
markdown: kramdown
highlighter: rouge
