# Site settings
title: Tim's Exploration Journal
email: timcandid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software developer with 10 years of experince in large-scale enterprise applications development and technical
  management; Sun Certified Java Developer, Scrum Alliance Certified Scrum Master, Python enthusiast and Scala novice.
  In this irregularly updated blog I keep notes of some of my findings, if I consider they might be useful for someone
  else.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://candidtim.github.io" # the base hostname & protocol for your site
twitter_username: candidtim
github_username:  candidtim

# Build settings
markdown: kramdown
highlighter: rouge
